[build-system]
requires = [
    "setuptools>=61.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "langid-pyc"
version = "0.0.4"
authors = [
    {name = "Aleksandr Lukoianov", email = "liablefish@gmail.com"}
]
description = "Python bindings for langid.c"

